### ISSUE TITLE
Finland OverflowError: math range error

### ISSUE THREAD

**Issue by BilelJegham** [RemiTheWarrior/epidemic-simulator#7]
- Run python3 fit_every_country.py
```
....
Finland
Fitting...
Traceback (most recent call last):966568
  File "fit_every_country.py", line 11, in <module>
    fit_country(country, save_to_json=True)
  File "/workspace/epidemic-simulator/fit_any_country.py", line 48, in fit_country
    res = scipy.optimize.minimize(cost_function, x0, method="Nelder-Mead")
  File "/workspace/.pip-modules/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 589, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 580, in _minimize_neldermead
    fxe = func(xe)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 300, in function_wrapper
    return function(*(wrapper_args + args))
  File "/workspace/epidemic-simulator/fit_any_country.py", line 22, in cost_function
    K_d_0=K_d_0, K_d_plus=0)
  File "/workspace/epidemic-simulator/epidemic.py", line 44, in calculate_epidemic
    x, y, z, d = fsolve(equations, (x_n, y_n, z_n, d_n))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 147, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 225, in _root_hybr
    ml, mu, epsfcn, factor, diag)
  File "/workspace/epidemic-simulator/epidemic.py", line 31, in equations
    s = (y-y_n)/dt - (K_c(v)*x*y - K_r(y) * y - K_d(y)*y)
  File "/workspace/epidemic-simulator/epidemic.py", line 20, in K_r
    return K_r_0 - K_r_minus/(1+math.exp(-100*(y - C)))
OverflowError: math range error
```

**Comment by RemDelaporteMathurin** [comment]
Fixed in #8
